### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by GhostLate** [naver/multi-hmr#15]
Thank you for your research.

Do you have any plans to release training and data processing code?

**Comment by jyuntins** [comment]
Looking forward to the training code, too.

**Comment by fabienbaradel** [comment]
Hi @jyuntins @GhostLate , thanks for your interest in our research, we really appreciate if Multi-HMR is useful for your project.
For the moment I cannot give you an exact timeline about when the training code will be released.
I will try to keep you updated on this issue, thanks 😃

**Comment by JiepengTan** [comment]
Thank you for your amazing research. I'm looking forward to the training code too.

**Comment by fabienbaradel** [comment]
Hi @JiepengTan @GhostLate @jyuntins , I am happy to share that today we are releasing training/evaluation code of Multi-HMR 😄 
We are providing code for training Multi-HMR on BEDLAM-train and evaluating on 3DPW-test, EHF and BEDLAM-validation.
Since this code release is solving this issue I am closing it, but feel free to re-open it if needed.
