### ISSUE TITLE
Hand Pose

### ISSUE THREAD

**Issue by sebastianopazo1** [naver/multi-hmr#19]
Hi! When trying to replicate the results on Unity I encountered some problems with the pose of the hands. 
![punjabi](https://github.com/naver/multi-hmr/assets/53013616/8433f5ca-bef8-47c0-b278-25a0d7299da9)
As you can see in the result on Unity the position of the hands and fingers doesn't look like the estimated in the output images. (Following image)
![ezgif-frame-028_multiHMR_896_L](https://github.com/naver/multi-hmr/assets/53013616/34b61957-2acd-44fa-801d-1b64a3adc52d)

I'm converting the values from rotation matrix to quaternions using the Pytorch3D library, specifically the function transforms.matrix_to_quaternion(). Do you think that it is a conversion problem or something else? 
Thanks for your help!

**Comment by fabienbaradel** [comment]
Hi, indeed. I think that it may comes from the fact that we we use ```flat_hand_mean=True``` (see [here](https://github.com/naver/multi-hmr/blob/master/blocks/smpl_layer.py#L38)) while maybe in your code you are using ```flat_hand_mean=False```. Depending on either you set this value to True of False it will not give the same mesh for the hand because it will apply the rotations starting from a flat hand mean or not.
I do not know exactly what is your code in Unity so that's a guess.
Hope that it helps,

**Comment by sebastianopazo1** [comment]
Hi! The problem was the order of the joints. The jaw was at the end, after the finger's joints.
