### ISSUE TITLE
SMPL Prediction

### ISSUE THREAD

**Issue by SWWdz** [naver/multi-hmr#38]
Can I change the prediction results from smplx to smpl? We should change it from parameters of smplx to smpl's parameters. Not only the mesh vertices. How can I do this?

**Comment by fabienbaradel** [comment]
Hi @SWWdz , we cannot directly give SMPL-X parameters to a SMPL model because the joints are not at the same location (please see [SMPLX github repo](https://github.com/vchoutas/smplx)). Instead you can us the SMPLX2SMPL regressor to move from the SMPLX mesh to the SMPL mesh. Then you would need to find the SMPL parameters using an optimization technique. Or you can use the conversion tool provided in the SMPLX page.
I hope that my answer helps,

**Comment by SWWdz** [comment]
Thanks for your answer!
